language: c
compiler:
  - gcc
  - clang

env:
  global:
    - secure: "Z/zUpt61heQFenJTfugXEbdMAcCRB9d+MaVI6bDpFX8jc6L3Glq6rqOchUBF/L7OMgOI1iBzOCVBX3cQ+MDoN/pdiYNDo8rWE54RY8LFbw48THR9xQMbqoCBpYnquzw6Kr3DDjYkzmOs3kiwD9Ui0F9y3d9eEqyuel2WF/BNGHG2z0zUlRDjyeyWQ7fxB+VH7F1veomGELTQfu7jOhdZmRH76uqh7V52+8AKTcK8MHI2H7F6eltKgab11/cJTtZgxsIx+hvfb8uUHZXRb4Zcs2YIG82lsGDocA4hHegVrI2tcJ3xVqsSC5jKTXA0C+/xrqn/bPAQfqu0O5cUSLtOv5RSPshgpENtiq2cBrtUTnnwfhKsKhgnYBZnKMhfBRtKSf1/Dvo4dvzCfFqV2Tl8nXknJSfVIaOEoJ1xdl5670vK5qt9M4aUWp6znImC3jL2IyCPeZTBAVWEWWK2EEsBKJsoKATEXIeGBKC/t2ELPaCeQVLUW3GlIoSxW5voXysMPu1vzZ1Wz2uH8kNYrGzIjHWHkMd8YLb8NOb/V5v2gEheArS9xb4p4ODkJw9E+GyvtB18sApfNg3+fkOQef9ju0keXAYQ88C+r3Bn3uuZd+tCm4OKfSIMXU63nbYEUx0ii+SUu9EpjYMoE/haxW17SwnxDVnGbqvSBGfJxRW4gWw="

addons:
  coverity_scan:
    project:
      name: ClamAV
      version: 0.99
      description: ClamAV
    notification_email: stevmorg@cisco.com
    build_command_prepend: ./configure
    build_command: make
    branch_pattern: coverity_scan

before_install:
  - sudo apt-get update -qq
  - > 
      sudo apt-get install --no-install-recommends -qq 
      libpcre3-dev
      libssl-dev
      libjson0-dev
      libxml2-dev
      check
      zlib1g-dev

install: ./configure --enable-check --with-libjson
script: if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then make check; fi
